# General Settings
title = "OD - CV Resume & Blogs"
baseURL = "https://odonfack.helep24.com" #YOUR SITE URL
languageCode = "en-us"
theme = "ryancv"
resourceDir = "resources"
paginate = 4
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
##
### to add or remove card (or menu item)
### param "name" - Menu item name
### param "pre" - Menu item icon class, all icons class you can see here https://ionicons.com/v4/
### param "identifier" - Menu item url slug
### param "url" - Menu item url
### param "sections" - list of sections what will be show of each card, all prebuild sections name see in documentations
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  pre = "ion-person"
  url = "#about-card"
  weight = 1
  [menu.main.params]
    builder = [
      "about",
      "services",
      "pricing",
      "facts",
      "clients",
      "testimonials"
    ]
[[menu.main]]
  identifier = "resume"
  name = "Resume"
  pre = "ion-android-list"
  url = "#resume-card"
  weight = 2
  [menu.main.params]
    builder = [
      "resume",
      "skills"
    ]
[[menu.main]]
  identifier = "works"
  name = "Works"
  pre = "ion-paintbrush"
  url = "#works-card"
  weight = 3
  [menu.main.params]
    builder = [
      "portfolio"
    ]
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  pre = "ion-chatbox-working"
  url = "#blog-card"
  weight = 4
  [menu.main.params]
    builder = [
      "blog"
    ]
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  pre = "ion-at"
  url = "#contact-card"
  weight = 5
  [menu.main.params]
    builder = [
      "contact-info",
      "contact-form"
    ]

[[menu.sidebar]]
  identifier = "blog"
  name = "Blog Page"
  url = "/blog/index.html"
  weight = 1
[[menu.sidebar]]
  identifier = "portfolio"
  name = "Portfolio Page"
  url = "/portfolio"
  weight = 2

# Main Settings
[params]
skinColor = "" #TEMPLATE SKIN COLOR: [ blue, green, orange, pink, purple, red ]. If empty colors taken from thenes/ryan/assets/scss/_settings.scss
skinDark = 0 #TEMPLATE UI: [ 1 - yes, 0 - no ]
rtl = 0 #TEMPLATE RTL MODE: [ 1 - yes, 0 - no ]
skinMinimal = 0 #TEMPLATE MINIMAL SKIN: [ 1 - yes, 0 - no ]
dateFormat = "January 2, 2006"
authorName = "Ryan Adlard"
disqusComments = "your_disqus_shortname" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "https://formspree.io/f/your_api_key" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Background
[params.background]
type = "default" #BACKGROUND TYPE: [ default, blured ]

# Google MAPS
[params.googleMaps]
key = "AIzaSyA0bT7YQ3lVsb3e4IXx6749E8--hZgL4vc" #YOUR GOOGLE MAPS API KEY: leave empty if you want to hide Google Maps
lat = "52.558246864926936" #YOUR GOOGLE MAPS LATITUDE
long = "13.182425184857076" #YOUR GOOGLE MAPS LONGITUDE
zoom = "14" #YOUR GOOGLE MAPS ZOOM VALUE

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
menuWidget = 1 #SIDEBAR MENU WIDGET: [ 1 - yes, 0 - no ]

# Animation Settings
[params.animation]
in = "fadeInLeft" #ANIMATION IN: [ rotateInUpLeft, rollIn, jackInTheBox, fadeIn, fadeInUp, fadeInLeft ]
out = "fadeOutLeft" #ANIMATION OUT: [ rotateOutUpLeft, rollOut, jackOutTheBox, fadeOut, fadeOutUp, fadeOutLeft ]

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "Photo"
slug = "photo"
[[params.portfolio.filters]]
name = "Video"
slug = "video"
[[params.portfolio.filters]]
name = "Music"
slug = "music"
[[params.portfolio.filters]]
name = "Design"
slug = "design"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "odonfackhelep24"
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://odonfack.helep24.com?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "EHB76WW6WSNR"


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true